### ISSUE TITLE
Failing install via pip

### ISSUE THREAD

**Issue by mattjhill** [hover2pi/svo_filters#4]
Looks like `astropy_helpers` expects there to be a `version.py` in the package root.
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/lx/6ws01y1s0yq5k7v6vy7pcpm80001rv/T/pip-build-z069kylx/svo-filters/setup.py", line 85, in <module>
        get_debug_option(PACKAGENAME))
      File "/private/var/folders/lx/6ws01y1s0yq5k7v6vy7pcpm80001rv/T/pip-build-z069kylx/svo-filters/astropy_helpers/astropy_helpers/version_helpers.py", line 268, in generate_version_py
        with open(version_py, 'w') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'svo_filters/version.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/lx/6ws01y1s0yq5k7v6vy7pcpm80001rv/T/pip-build-z069kylx/svo-filters/
```

**Comment by hover2pi** [comment]
Moved it to root (416d548)
